#include<iostream.h>
#include<conio.h>

int n1, n2, resultados, resultadom;
	void main()
{
cout<<"RESULTADO DE SUMA Y MULTIPLICACION.\n";
  	cout<<"Ingrese Primer numero real: ";
   cin>>n1;
 	cout<<"Ingrese Segundo numero real: ";cin>>n2;
   resultados=n1+n2;
   cout<<"-La suma de los numeros enteros es: "<<resultados;
   resultadom=n1*n2;
   cout<<"-La multiplicacion de los numeros enteros es: "<<resultadom;
   getch();
return;
}
