#include<iostream.h>
#include<conio.h>

int num,cont=1,mul;

void main()
{
  	cout<<" INTRODUCE QUE TABLA DE MULTIPLICAR NECESITAS :""\n";
	cin>>num;

if (mul=(num<=10))
{



  mul=cont*num;
  cout<<"\n";
  cout<<num;
  cout<<"x";
  cout<<cont;
  cout<<"=";
  cout<<mul;
  cont=1*2;

  mul=cont*num;
  cout<<"\n";
  cout<<num;
  cout<<"x";
  cout<<cont;
  cout<<"=";
  cout<<mul;
  cont=1*3;

  mul=cont*num;
  cout<<"\n";
  cout<<num;
  cout<<"x";
  cout<<cont;
  cout<<"=";
  cout<<mul;
  cont=1*4;

  mul=cont*num;
  cout<<"\n";
  cout<<num;
  cout<<"x";
  cout<<cont;
  cout<<"=";
  cout<<mul;
  cont=1*5;

  mul=cont*num;
  cout<<"\n";
  cout<<num;
  cout<<"x";
  cout<<cont;
  cout<<"=";
  cout<<mul;
  cont=1*6;

  mul=cont*num;
  cout<<"\n";
  cout<<num;
  cout<<"x";
  cout<<cont;
  cout<<"=";
  cout<<mul;
  cont=1*7;

  mul=cont*num;
  cout<<"\n";
  cout<<num;
  cout<<"x";
  cout<<cont;
  cout<<"=";
  cout<<mul;
  cont=1*8;

  mul=cont*num;
  cout<<"\n";
  cout<<num;
  cout<<"x";
  cout<<cont;
  cout<<"=";
  cout<<mul;
  cont=1*9;

  mul=cont*num;
  cout<<"\n";
  cout<<num;
  cout<<"x";
  cout<<cont;
  cout<<"=";
  cout<<mul;
  cont=1*10;

    mul=cont*num;
  cout<<"\n";
  cout<<num;
  cout<<"x";
  cout<<cont;
  cout<<"=";
  cout<<mul;
  cont=10*10;

}
else
{
cout<<"ya no ay xd";
}

getch();
return;
}